- name: Configure WireGuard VPN
  hosts: vpn
  become: yes
  tasks:
    - name: Install WireGuard
      apt:
        name: wireguard
        state: present
        update_cache: yes

    - name: Enable IP forwarding
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward='
        line: 'net.ipv4.ip_forward=1'
      notify: Restart sysctl

    - name: Generate WireGuard keys
      shell: |
        wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
        chmod 600 /etc/wireguard/privatekey
      args:
        creates: /etc/wireguard/privatekey

    - name: Read WireGuard private key
      slurp:
        src: /etc/wireguard/privatekey
      register: privatekey_content

    - name: Read WireGuard public key
      slurp:
        src: /etc/wireguard/publickey
      register: publickey_content

    - name: Output server public key
      debug:
        msg: "Server public key is: {{ publickey_content['content'] | b64decode }}"

    - name: Configure WireGuard
      copy:
        dest: /etc/wireguard/wg0.conf
        content: |
          [Interface]
          PrivateKey = {{ privatekey_content['content'] | b64decode }}
          Address = 10.0.0.1/24
          ListenPort = 51820
          PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
          PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
          SaveConfig = true

    - name: Start WireGuard
      service:
        name: wg-quick@wg0
        state: started
        enabled: yes

  handlers:
    - name: Restart sysctl
      command: sysctl -p
